# #+Title: Implementation of *experiment server* project  
# #+Author: Sytems Team
# #+SETUPFILE: ../org-templates/level-1.org
# #+TAGS: boilerplate(b)
# #+EXCLUDE_TAGS: boilerplate
# #+OPTIONS: ^:nil
# # !/usr/bin/env zsh
# # -*- mode: shell-script -*-

# * Introduction
#   This document contains the implementation of *experiment server* project  
# * Implementation
# ** Steps to Ceate a VM on base4
#    - Open terminal login to base4 with the below command:
# # sudo apt-get install sshpass

# # export SSHPASS="9705651490s"
# # sshpass -e ssh -oBatchMode=no modepusravanthi@10.4.12.24
# # #+END_SRC  
# #    - Enter into the root from the container using the below command.
# #+BEGIN_SRC
# ssh modepusravanthi@10.4.12.24
# sudo su -
# #+END_SRC

#    - Create a container on base4 with below command:  
# #+BEGIN_SRC
# vzctl create 31 --ostemplate ubuntu-14.04-x86_64 --ipadd 10.4.12.31 --hostname experiment-server-labs
# #+END_SRC

#    - Then start the container as:
# #+BEGIN_SRC
# vzctl start 31
# #+END_SRC
#    - Enter into the container as :
# #+BEGIN_SRC
# vzctl enter 31
# #+END_SRC
   
# ** Json file with list of experiment server labs

# #+BEGIN_SRC json :tangle labs.json

# [
#   {
#     "Lab_ID": "fm-nitk",
#     "Lab_Url": "http://fm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fluid-mechanics-nitk",
#     "Lab Name": "Fluid Mechanics"
#   },
#   {
#     "Lab_ID": "fmc-nitk",
#     "Lab_Url": "http://fmc-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fluid-machinery-lab-nitk",
#     "Lab Name": "Fluid Machinery Lab"
#   },
#   {
#     "Lab_ID": "mfts-iitg",
#     "Lab_Url": "https://mfts-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-laboratory-experience-in-fluid-and-thermal-sciences-iitg",
#     "Lab Name": "Virtual laboratory Experience in Fluid and Thermal Sciences"
#   },
#   {
#     "Lab_ID": "mv-iitg",
#     "Lab_Url": "https://mv-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-lab-for-mechanical-vibrations-iitg",
#     "Lab Name": "Virtual Lab for Mechanical Vibrations"
#   },
#   {
#     "Lab_ID": "vmt-iitg",
#     "Lab_Url": "https://vmt-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-mass-transfer-lab-iitg",
#     "Lab Name": "Virtual Mass Transfer"
#   },
#   {
#     "Lab_ID": "ve-iitg",
#     "Lab_Url": "https://ve-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-english-iitg",
#     "Lab Name": "Virtual English and Communication Lab"
#   },
#   {
#     "Lab_ID": "ergonomics-iitg",
#     "Lab_Url": "https://ergonomics-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/ergonomics-iitg",
#     "Lab Name": "Ergonomics Lab for Assessing Physical Aspects of Design"
#   },
#   {
#     "Lab_ID": "vlsi-iitg",
#     "Lab_Url": "https://vlsi-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/digital-vlsi-design-iitg",
#     "Lab Name": "Digital VLSI Design Virtual lab"
#   },
#   {
#     "Lab_ID": "ssl-iitg",
#     "Lab_Url": "https://ssl-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/signals-and-systems-laboratory-iitg",
#     "Lab Name": "Signals and Systems Laboratory"
#   },
#   {
#     "Lab_ID": "vem-iitg",
#     "Lab_Url": "https://vem-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/electrical-machines-iitg",
#     "Lab Name": "Electrical Machines Laboratory"
#   },
#   {
#     "Lab_ID": "anthropology-iitg",
#     "Lab_Url": "https://anthropology-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/anthropology-iitg",
#     "Lab Name": "Virtual Anthropology Lab"
#   },
#   {
#     "Lab_ID": "he-coep",
#     "Lab_Url": "https://he-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/hybrid-electronics-lab-coep",
#     "Lab Name": "Hybrid Electronics Lab"
#   },
#   {
#     "Lab_ID": "sl-coep",
#     "Lab_Url": "https://sl-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/sensor-laboratory-coep",
#     "Lab Name": "Sensor Lab"
#   },
#   {
#     "Lab_ID": "va-coep",
#     "Lab_Url": "https://va-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/vibration-and-acoustics-coep",
#     "Lab Name": "Vibration and Acoustics"
#   },
#   {
#     "Lab_ID": "plc-coep",
#     "Lab_Url": "https://plc-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/programmable-logic-controller-coep",
#     "Lab Name": "Programmable Logic Controller Lab"
#   },
#   {
#     "Lab_ID": "em-coep",
#     "Lab_Url": "https://em-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/electrical-machines-coep",
#     "Lab Name": "Electrical Machines Lab"
#   },
#   {
#     "Lab_ID": "mm-coep",
#     "Lab_Url": "https://mm-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/micro-machining-laboratory-coep",
#     "Lab Name": "Micromachining laboratory"
#   },
#   {
#     "Lab_ID": "fab-coep",
#     "Lab_Url": "https://fab-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fab-laboratory-coep",
#     "Lab Name": "FAB laboratory!"
#   },
#   {
#     "Lab_ID": "sm-nitk",
#     "Lab_Url": "https://sm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/strength-of-materials-nitk",
#     "Lab Name": "Strength-of-Materials lab"
#   },
#   {
#     "Lab_ID": "ied-nitk",
#     "Lab_Url": "https://ied-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/industrial-electrical-drives-nitk",
#     "Lab Name": "Industrial Electric Drives and Application of PLC"
#   },
#   {
#     "Lab_ID": "mm-nitk",
#     "Lab_Url": "https://mm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/mechanics-of-machine-nitk",
#     "Lab Name": "Mechanics of Machine lab"
#   },
#   {
#     "Lab_ID": "mdmv-nitk",
#     "Lab_Url": "https://mdmv-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/machine-dynamics-and-mechanical-vibrations-nitk",
#     "Lab Name": "Machine Dynamics and Mechanical Vibrations Lab"
#   },
#   {
#     "Lab_ID": "sa-nitk",
#     "Lab_Url": "https://sa-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/substration-automation-nitk",
#     "Lab Name": "Substation Automation lab"
#   },
#   {
#     "Lab_ID": "mrmsmtbs-iitk",
#     "Lab_Url": "https://mrmsmtbs-iitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-thermal-and-biological-stimuli-iitk",
#     "Lab Name": "Material Response to Microstructural,Mechanical, Thermal and Biological Stimuli"
#   },
#   {
#     "Lab_ID": "uorepc-nitk",
#     "Lab_Url": "https://uorepc-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and¡Vprocess-control-nitk",
#     "Lab Name": "Unit-Operation-Reaction-Engg.-Process-Control lab"
#   },
#   {
#     "Lab_ID": "tel-iitb",
#     "Lab_Url": "https://tel-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/traffic-engg-iitb",
#     "Lab Name": "Traffic Engineering Laboratory"
#   },
#   {
#     "Lab_ID": "mfs-iiith",
#     "Lab_Url": "https://mfs-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith",
#     "Lab Name": "Molecular Fluorescence Spectroscopy"
#   },
#   {
#     "Lab_ID": "ml-iitb",
#     "Lab_Url": "https://ml-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/maglev-iitb",
#     "Lab Name": "Magnetic Levitation"
#   },
#   {
#     "Lab_ID": "pe-iitb",
#     "Lab_Url": "https://pe-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/protein-engg-iitb",
#     "Lab Name": "Virtual Proteomics Laboratory"
#   },
#   {
#     "Lab_ID": "cse01-iiith",
#     "Lab_Url": "https://cse01-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/data-structures-iiith",
#     "Lab Name": "Data Structures"
#   },
#   {
#     "Lab_ID": "mas-iiith",
#     "Lab_Url": "https://mas-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab",
#     "Lab Name": "Molecular Absorption Spectroscopy Lab"
#   }
# ]
# #+END_SRC 

# ** Automation script for the experiment server labs
#    - Read the lab names from the file labs.json and clone the labs.

# - Initially the below python code imports the required modules to run the script.
# #+BEGIN_SRC python :tangle automation.py
# import json
# import sys
# import os
# import os.path
# from pprint import pprint
# from git import Repo
# import git
# #+END_SRC

# - Assigning variables in the script
# #+BEGIN_SRC python :tangle automation.py
# exp_id = "../exp-ids"
# labs = "../exp-server-labs"
# #+END_SRC

# - variable to store proxy value
# #+BEGIN_SRC python :tangle automation.py
# proxy = "http://proxy.iiit.ac.in:8080"
# #+END_SRC

# - setup proxy to install required module
# #+BEGIN_SRC python :tangle automation.py
# os.environ["HTTP_PROXY"] = proxy
# os.environ["HTTPS_PROXY"] = proxy
# #+END_SRC

# - Create directories to store experiment Id's and repositories
#    - exp-ids : to strore exp-ids
#    - exp-server-labs : to store all the repositories 
# #+BEGIN_SRC python :tangle automation.py
# os.makedirs('../exp-server-labs')
# os.makedirs('../exp-ids')
# #+END_SRC

# - Open and read the json file to get exp-ids and repositories
# #+BEGIN_SRC python :tangle automation.py
# with open('labs.json') as data_file:
#     data = json.load(data_file)
# #+END_SRC

# - Prints exp-ids    
# #+BEGIN_SRC python :tangle automation.py
#     for i in range(5):
#         os.chdir(exp_id)
#         if not os.path.isdir("exp_id[i]"):
#             repo_id = data[i]["Lab_ID"]
#             pprint (repo_id)

# #+END_SRC

# - Clones all the repositories in the "experiment-sever-labs" directory
# #+BEGIN_SRC python :tangle automation.py
#     os.chdir(labs)
#     for i in range(5):
#         if not os.path.isdir("labs[i]"):
#             os.system("git clone %s" % data[i]["Github_Url"])            
# #+END_SRC

# - Splitting the github url and taking the repository name to run makefile in the repository
# #+BEGIN_SRC python :tangle automation.py
#             repo_name = data[i]["Github_Url"].split("/")[-1]
#             pprint (repo_name)

# #+END_SRC

# - Reads each repository to run make file            
# #+BEGIN_SRC python :tangle automation.py
#             os.chdir(repo_name)                 
#             if not os.path.isdir(repo_name):          
#                 cmd1 = "make -C src/"
#                 os.system(cmd1)
#                 lab_id= data[i]["Lab_ID"]
# #+END_SRC

# - Copies build folder to "/var/www/"
# #+BEGIN_SRC python :tangle automation.py
#                 cmd2 = "sudo rsync -rav build/* " + "/var/www/" + lab_id + "/"
#                 #pprint (cmd2)
#                 os.system(cmd2)
#                 # pprint (cmd)
#                 #cmd = "cd .."
#                 os.chdir("..")
# #+END_SRC

# ** Usage of Python Script
# - Install and setup git from a [[https://githowto.com/][Git]] intallation Guide
# - Go to https://gitlab.com/vlead-systems copy the link [[https://gitlab.com/vlead-systems/experiment-server/][experiment-serve]]r 
# - Go to terminal and type below command to clone the repository
# #+BEGIN_EXAMPLE
# git clone https://gitlab.com/vlead-systems/experiment-server/
# #+END_EXAMPLE
# - Change the directory to "build-vlabs-on-openedx/src/implemetation/"
# - Open index.org in org mode to make appropriate changes.
# - Following changes need to be done in the automation.py
# #+BEGIN_EXAMPLE
# - setup "proxy" according to the network.
# - Change variables and range accordingly
# #+END_EXAMPLE
# - After the changes made in the index.org file, get back to the
#   expeirment-server-labs drectory and run make file.
# - A build folder is generated in expeirment-server-labs.  
# - Inside the build/code/implementation, two files are generated namely
#   automation.py and labs.json.  
# - Run python file with below command:
# #+BEGIN_EXAMPLE
# python autmation.py
# #+END_EXAMPLE
# ** Output of the script
# - Prints exp-ids 
# - Clones all the repositories in the "exp-server-labs" directory
# - Reads each repository and runs makefile 
# - Then the generated build folder is copied to "/var/www/" 
#+Title: Implementation of *experiment server* project  
#+Author: Sytems Team
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil
# !/usr/bin/env zsh
# -*- mode: shell-script -*-

* Introduction
  This document contains the implementation of *experiment server* project  
* Implementation
** Steps to Ceate a VM on base4
   - Open terminal login to base4 with the below command:
# sudo apt-get install sshpass

# export SSHPASS="9705651490s"
# sshpass -e ssh -oBatchMode=no modepusravanthi@10.4.12.24
# #+END_SRC  
#    - Enter into the root from the container using the below command.
#+BEGIN_SRC
ssh modepusravanthi@10.4.12.24
sudo su -
#+END_SRC

   - Create a container on base4 with below command:  
#+BEGIN_SRC
vzctl create 31 --ostemplate ubuntu-14.04-x86_64 --ipadd 10.4.12.31 --hostname experiment-server-labs
#+END_SRC

   - Then start the container as:
#+BEGIN_SRC
vzctl start 31
#+END_SRC
   - Enter into the container as :
#+BEGIN_SRC
vzctl enter 31
#+END_SRC

** CSV file to read the data with python script
#+BEGIN_src csv :tangle labs.csv
fm-nitk,http://fm-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/fluid-mechanics-nitk,Fluid Mechanics
fmc-nitk,http://fmc-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/fluid-machinery-lab-nitk,Fluid Machinery Lab
mfts-iitg,https://mfts-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/virtual-laboratory-experience-in-fluid-and-thermal-sciences-iitg,Virtual laboratory Experience in Fluid and Thermal Sciences
mv-iitg,https://mv-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/virtual-lab-for-mechanical-vibrations-iitg,Virtual Lab for Mechanical Vibrations
vmt-iitg,https://vmt-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/virtual-mass-transfer-lab-iitg,Virtual Mass Transfer
ve-iitg,https://ve-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/virtual-english-iitg,Virtual English and Communication Lab
ergonomics-iitg,https://ergonomics-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/ergonomics-iitg,Ergonomics Lab for Assessing Physical Aspects of Design
vlsi-iitg,https://vlsi-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/digital-vlsi-design-iitg,Digital VLSI Design Virtual lab
ssl-iitg,https://ssl-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/signals-and-systems-laboratory-iitg,Signals and Systems Laboratory
vem-iitg,https://vem-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/electrical-machines-iitg,Electrical Machines Laboratory
anthropology-iitg,https://anthropology-iitg.vlabs.ac.in,https://github.com/Virtual-Labs/anthropology-iitg,Virtual Anthropology Lab
he-coep,https://he-coep.vlabs.ac.in,https://github.com/Virtual-Labs/hybrid-electronics-lab-coep,Hybrid Electronics Lab
sl-coep,https://sl-coep.vlabs.ac.in,https://github.com/Virtual-Labs/sensor-laboratory-coep,Sensor Lab
va-coep,https://va-coep.vlabs.ac.in,https://github.com/Virtual-Labs/vibration-and-acoustics-coep,Vibration and Acoustics
plc-coep,https://plc-coep.vlabs.ac.in,https://github.com/Virtual-Labs/programmable-logic-controller-coep,Programmable Logic Controller Lab
em-coep,https://em-coep.vlabs.ac.in,https://github.com/Virtual-Labs/electrical-machines-coep,Electrical Machines Lab
mm-coep,https://mm-coep.vlabs.ac.in,https://github.com/Virtual-Labs/micro-machining-laboratory-coep,Micromachining laboratory
fab-coep,https://fab-coep.vlabs.ac.in,https://github.com/Virtual-Labs/fab-laboratory-coep,FAB laboratory!
sm-nitk,https://sm-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/strength-of-materials-nitk,Strength-of-Materials lab
ied-nitk,https://ied-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/industrial-electrical-drives-nitk,Industrial Electric Drives and Application of PLC
mm-nitk,https://mm-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/mechanics-of-machine-nitk,Mechanics of Machine lab
mdmv-nitk,https://mdmv-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/machine-dynamics-and-mechanical-vibrations-nitk,Machine Dynamics and Mechanical Vibrations Lab
sa-nitk,https://sa-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/substration-automation-nitk,Substation Automation lab
mrmsmtbs-iitk,https://mrmsmtbs-iitk.vlabs.ac.in,https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-thermal-and-biological-stimuli-iitk,"Material Response to Microstructural,Mechanical, Thermal and Biological Stimuli"
uorepc-nitk,https://uorepc-nitk.vlabs.ac.in,https://github.com/Virtual-Labs/unit-operation-reaction-engineering-and–process-control-nitk,Unit-Operation-Reaction-Engg.-Process-Control lab
tel-iitb,https://tel-iitb.vlabs.ac.in,https://github.com/Virtual-Labs/traffic-engg-iitb,Traffic Engineering Laboratory
mfs-iiith,https://mfs-iiith.vlabs.ac.in,https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith,Molecular Fluorescence Spectroscopy
ml-iitb,https://ml-iitb.vlabs.ac.in,https://github.com/Virtual-Labs/maglev-iitb,Magnetic Levitation
pe-iitb,https://pe-iitb.vlabs.ac.in,https://github.com/Virtual-Labs/protein-engg-iitb,Virtual Proteomics Laboratory
cse01-iiith,https://cse01-iiith.vlabs.ac.in,https://github.com/Virtual-Labs/data-structures-iiith,Data Structures
mas-iiith,https://mas-iiith.vlabs.ac.in,https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab,Molecular Absorption Spectroscopy Lab
#+END_SRC

** Json file to read data with python script
# #+BEGIN_SRC json :tangle labs.json
# - file with list of experiment server labs

# [
#   {
#     "Lab_ID": "fm-nitk",
#     "Lab_Url": "http://fm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fluid-mechanics-nitk",
#     "Lab Name": "Fluid Mechanics"
#   },
#   {
#     "Lab_ID": "fmc-nitk",
#     "Lab_Url": "http://fmc-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fluid-machinery-lab-nitk",
#     "Lab Name": "Fluid Machinery Lab"
#   },
#   {
#     "Lab_ID": "mfts-iitg",
#     "Lab_Url": "https://mfts-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-laboratory-experience-in-fluid-and-thermal-sciences-iitg",
#     "Lab Name": "Virtual laboratory Experience in Fluid and Thermal Sciences"
#   },
#   {
#     "Lab_ID": "mv-iitg",
#     "Lab_Url": "https://mv-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-lab-for-mechanical-vibrations-iitg",
#     "Lab Name": "Virtual Lab for Mechanical Vibrations"
#   },
#   {
#     "Lab_ID": "vmt-iitg",
#     "Lab_Url": "https://vmt-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-mass-transfer-lab-iitg",
#     "Lab Name": "Virtual Mass Transfer"
#   },
#   {
#     "Lab_ID": "ve-iitg",
#     "Lab_Url": "https://ve-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/virtual-english-iitg",
#     "Lab Name": "Virtual English and Communication Lab"
#   },
#   {
#     "Lab_ID": "ergonomics-iitg",
#     "Lab_Url": "https://ergonomics-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/ergonomics-iitg",
#     "Lab Name": "Ergonomics Lab for Assessing Physical Aspects of Design"
#   },
#   {
#     "Lab_ID": "vlsi-iitg",
#     "Lab_Url": "https://vlsi-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/digital-vlsi-design-iitg",
#     "Lab Name": "Digital VLSI Design Virtual lab"
#   },
#   {
#     "Lab_ID": "ssl-iitg",
#     "Lab_Url": "https://ssl-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/signals-and-systems-laboratory-iitg",
#     "Lab Name": "Signals and Systems Laboratory"
#   },
#   {
#     "Lab_ID": "vem-iitg",
#     "Lab_Url": "https://vem-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/electrical-machines-iitg",
#     "Lab Name": "Electrical Machines Laboratory"
#   },
#   {
#     "Lab_ID": "anthropology-iitg",
#     "Lab_Url": "https://anthropology-iitg.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/anthropology-iitg",
#     "Lab Name": "Virtual Anthropology Lab"
#   },
#   {
#     "Lab_ID": "he-coep",
#     "Lab_Url": "https://he-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/hybrid-electronics-lab-coep",
#     "Lab Name": "Hybrid Electronics Lab"
#   },
#   {
#     "Lab_ID": "sl-coep",
#     "Lab_Url": "https://sl-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/sensor-laboratory-coep",
#     "Lab Name": "Sensor Lab"
#   },
#   {
#     "Lab_ID": "va-coep",
#     "Lab_Url": "https://va-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/vibration-and-acoustics-coep",
#     "Lab Name": "Vibration and Acoustics"
#   },
#   {
#     "Lab_ID": "plc-coep",
#     "Lab_Url": "https://plc-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/programmable-logic-controller-coep",
#     "Lab Name": "Programmable Logic Controller Lab"
#   },
#   {
#     "Lab_ID": "em-coep",
#     "Lab_Url": "https://em-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/electrical-machines-coep",
#     "Lab Name": "Electrical Machines Lab"
#   },
#   {
#     "Lab_ID": "mm-coep",
#     "Lab_Url": "https://mm-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/micro-machining-laboratory-coep",
#     "Lab Name": "Micromachining laboratory"
#   },
#   {
#     "Lab_ID": "fab-coep",
#     "Lab_Url": "https://fab-coep.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/fab-laboratory-coep",
#     "Lab Name": "FAB laboratory!"
#   },
#   {
#     "Lab_ID": "sm-nitk",
#     "Lab_Url": "https://sm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/strength-of-materials-nitk",
#     "Lab Name": "Strength-of-Materials lab"
#   },
#   {
#     "Lab_ID": "ied-nitk",
#     "Lab_Url": "https://ied-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/industrial-electrical-drives-nitk",
#     "Lab Name": "Industrial Electric Drives and Application of PLC"
#   },
#   {
#     "Lab_ID": "mm-nitk",
#     "Lab_Url": "https://mm-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/mechanics-of-machine-nitk",
#     "Lab Name": "Mechanics of Machine lab"
#   },
#   {
#     "Lab_ID": "mdmv-nitk",
#     "Lab_Url": "https://mdmv-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/machine-dynamics-and-mechanical-vibrations-nitk",
#     "Lab Name": "Machine Dynamics and Mechanical Vibrations Lab"
#   },
#   {
#     "Lab_ID": "sa-nitk",
#     "Lab_Url": "https://sa-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/substration-automation-nitk",
#     "Lab Name": "Substation Automation lab"
#   },
#   {
#     "Lab_ID": "mrmsmtbs-iitk",
#     "Lab_Url": "https://mrmsmtbs-iitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/material-response-to-micro-structural-mechanical-thermal-and-biological-stimuli-iitk",
#     "Lab Name": "Material Response to Microstructural,Mechanical, Thermal and Biological Stimuli"
#   },
#   {
#     "Lab_ID": "uorepc-nitk",
#     "Lab_Url": "https://uorepc-nitk.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/unit-operation-reaction-engineering-andVprocess-control-nitk",
#     "Lab Name": "Unit-Operation-Reaction-Engg.-Process-Control lab"
#   },
#   {
#     "Lab_ID": "tel-iitb",
#     "Lab_Url": "https://tel-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/traffic-engg-iitb",
#     "Lab Name": "Traffic Engineering Laboratory"
#   },
#   {
#     "Lab_ID": "mfs-iiith",
#     "Lab_Url": "https://mfs-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/molecular-florescence-spectroscopy-responsive-lab-iiith",
#     "Lab Name": "Molecular Fluorescence Spectroscopy"
#   },
#   {
#     "Lab_ID": "ml-iitb",
#     "Lab_Url": "https://ml-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/maglev-iitb",
#     "Lab Name": "Magnetic Levitation"
#   },
#   {
#     "Lab_ID": "pe-iitb",
#     "Lab_Url": "https://pe-iitb.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/protein-engg-iitb",
#     "Lab Name": "Virtual Proteomics Laboratory"
#   },
#   {
#     "Lab_ID": "cse01-iiith",
#     "Lab_Url": "https://cse01-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/data-structures-iiith",
#     "Lab Name": "Data Structures"
#   },
#   {
#     "Lab_ID": "mas-iiith",
#     "Lab_Url": "https://mas-iiith.vlabs.ac.in",
#     "Github_Url": "https://github.com/Virtual-Labs/molecular-absorption-spectroscopy-responsive-lab",
#     "Lab Name": "Molecular Absorption Spectroscopy Lab"
#   }
# ]

# #+END_SRC

** Automation script for the experiment server labs
   - Read the lab names from the file labs.json and clone the labs.
- Initially the below python code imports the required modules to run the script.
#+BEGIN_SRC python :tangle automation.py
import csv
import json
import sys
import os
import os.path
from pprint import pprint
from git import Repo
import git
#+END_SRC

- Assigning variables in the script
#+BEGIN_SRC python :tangle automation.py
exp_id = "../exp-ids"
labs = "../exp-server-labs"
#+END_SRC

- variable to store proxy value
#+BEGIN_SRC python :tangle automation.py
proxy = "http://proxy.iiit.ac.in:8080"
#+END_SRC

- setup proxy to install required module
#+BEGIN_SRC python :tangle automation.py
os.environ["HTTP_PROXY"] = proxy
os.environ["HTTPS_PROXY"] = proxy
#+END_SRC

- Create directories to store experiment Id's and repositories
   - exp-ids : to strore exp-ids
   - exp-server-labs : to store all the repositories 
#+BEGIN_SRC python :tangle automation.py
os.makedirs('../exp-server-labs')
os.makedirs('../exp-ids')
#+END_SRC

- Open and read the json file to get exp-ids and repositories
#+BEGIN_SRC python :tangle automation.py
with open('labs.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',') 
    for row in readCSV:
        pprint(row)
#+END_SRC

- Prints exp-ids    
#+BEGIN_SRC python :tangle automation.py
    for i in range(5):
        # os.chdir(exp_id)
        # if not os.path.isdir("exp_id[i]"):
        repo_id = readcsv["Lab_ID"]
        pprint (repo_id)

#+END_SRC

- Clones all the repositories in the "experiment-sever-labs" directory
#+BEGIN_SRC python :tangle automation.py     
    os.chdir(labs)
    for i in range(5):
        if not os.path.isdir("labs[i]"):
            os.system("git clone %s" % readcsv["Github_Url"])            
#+END_SRC

- Splitting the github url and taking the repository name to run makefile in the repository
#+BEGIN_SRC python :tangle automation.py
            repo_name = data[i]["Github_Url"].split("/")[-1]
            pprint (repo_name)

#+END_SRC

- Reads each repository to run make file            
#+BEGIN_SRC python :tangle automation.py
            os.chdir(repo_name)                 
            if not os.path.isdir(repo_name):          
                cmd1 = "make -C src/"
                os.system(cmd1)
                lab_id= readcsv["Lab_ID"]
#+END_SRC

- Copies build folder to "/var/www/"
#+BEGIN_SRC python :tangle automation.py
                cmd2 = "sudo rsync -rav build/* " + "/var/www/" + lab_id + "/"
                #pprint (cmd2)
                os.system(cmd2)
                #  pprint (cmd)
                #cmd = "cd .."
                os.chdir("..")
#+END_SRC

** Usage of Python Script
- Install and setup git from a [[https://githowto.com/][Git]] intallation Guide
- Go to https://gitlab.com/vlead-systems copy the link [[https://gitlab.com/vlead-systems/experiment-server/][experiment-serve]]r 
- Go to terminal and type below command to clone the repository
#+BEGIN_EXAMPLE
git clone https://gitlab.com/vlead-systems/experiment-server/
#+END_EXAMPLE
- Change the directory to "build-vlabs-on-openedx/src/implemetation/"
- Open index.org in org mode to make appropriate changes.
- Following changes need to be done in the automation.py
#+BEGIN_EXAMPLE
- setup "proxy" according to the network.
- Change variables and range accordingly
#+END_EXAMPLE
- After the changes made in the index.org file, get back to the
  expeirment-server-labs drectory and run make file.
- A build folder is generated in expeirment-server-labs.  
- Inside the build/code/implementation, two files are generated namely
  automation.py and labs.json.  
- Run python file with below command:
#+BEGIN_EXAMPLE
python autmation.py
#+END_EXAMPLE
** Output of the script
- Prints exp-ids 
- Clones all the repositories in the "exp-server-labs" directory
- Reads each repository and runs makefile 
- Then the generated build folder is copied to "/var/www/" 
